### ISSUE TITLE
Remove path append hardcoded dependency

### ISSUE THREAD

**Issue by ivansabik** [ivansabik/featkeeper#1]
Change 

```python
sys.path.append('/home/ivansabik/Desktop/featkeeper')
```
for something that works in all envs
`

**Comment by ivansabik** [comment]
When using dev env with other path, doesnt work!

`ImportError: No module named featkeeper
`

**Comment by ivansabik** [comment]
Travis error cause of this:

https://travis-ci.org/ivansabik/featkeeper/jobs/113027594

```
Traceback (most recent call last):
  File "featkeeper/api.py", line 3, in <module>
    from models import FeatureRequest
  File "/home/travis/build/ivansabik/featkeeper/featkeeper/models.py", line 3, in <module>
    from mongothon import *
```

**Comment by ivansabik** [comment]
Could do setup.py or add dynamically path, when implementing coverage maybe it's better setup.py

**Comment by ivansabik** [comment]
Finally solved in https://github.com/ivansabik/featkeeper/commit/db6f4e13212fecccf51907cd790f434964660f29

+sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/' + '../..'))
